#!/bin/bash

total_uncommitted=0

if [[ $# -gt 0 ]]; then

  for basedir in "$@"; do
    if [ -d $basedir ]; then
      for d in $(find -H $basedir -type d -name .hg -o -name .git |sed 's#/\.hg\|/\.git##' |sort); do

        # hg
        if [ -d "$d/.hg" ]; then
          uncommitted=$(hg status -R $d)
        # git
        elif [ -d "$d/.git" ]; then
          uncommitted=$(git -C $d status |grep 'modified:' |sed 's/\tmodified:   /M /')
        fi    

        if [[ $? -eq 0 && -n $uncommitted ]]; then
          echo -e "\033[1;34m$d\033[0m"
          echo "$uncommitted"
          let total_uncommitted++
        fi

      done
    fi
  done

else

  echo "Usage: $(basename $0) directory" >&2
  exit 1

fi

exit $total_uncommitted
